### ISSUE TITLE
The font problem of the korean

### ISSUE THREAD

**Issue by issac4892** [FreeDownloadManagerTeam/FDM6-localization#129]
The font used for now is the one that is really uncomfortable. So it will be good if it gets changed.
[NanumGothic.zip](https://github.com/FreeDownloadManagerTeam/FDM6-localization/files/5333268/NanumGothic.zip)
It will be good if you use this one.

**Comment by BestiaPL** [comment]
But this one is badly look with EastEuropean codepages... look at the attached picture.
![nanum_gothic_font](https://user-images.githubusercontent.com/26287042/95250239-1934e180-081a-11eb-96f9-47fb723983e7.PNG)

But maybe you are right - maybe this is moment for change font to Unicode one.

**Comment by issac4892** [comment]
it will be good if they set the font for only the unicode ;(

**Comment by lychichem** [comment]
@issac4892 As far as I know, font used in FDM is not included in this translation repository. It's related to the program sourcecode. Maybe you should contact the team with an email and let them use a font that is friendly to both CJK characters and latin characters.
