### ISSUE TITLE
Problems unable to translate

### ISSUE THREAD

**Issue by VenusGirl** [FreeDownloadManagerTeam/FDM6-localization#151]
1. There should be a string for the theme selection.
![fdm01](https://user-images.githubusercontent.com/53147200/99665684-50e7a800-2aad-11eb-8a7b-f3ab3944e0c7.png)

2. There must be a string for tag editing.
![fdm02](https://user-images.githubusercontent.com/53147200/99666055-ca7f9600-2aad-11eb-8b32-5f9d83021691.png)

3. When tag is added, it is not displayed in the properly translated language.
![fdm03](https://user-images.githubusercontent.com/53147200/99666152-ef740900-2aad-11eb-8c44-a0de2e5473c5.png)

**Comment by FreeDownloadManagerTeam** [comment]
Thanks for the report! The problems will be fixed in the next release.
Please use the support system to report bugs.
