### ISSUE TITLE
Not translated string, wrong path name

### ISSUE THREAD

**Issue by BestiaPL** [FreeDownloadManagerTeam/FDM6-localization#153]
Hello.
I found two bugs:
1) one string is not published for translating (in settings window) - about themes
2) user can set download path, but on Win10 x64 path should use backslash, not slash (like Unix/Linux).

Bot issues are marked on attached image.
![fdm](https://user-images.githubusercontent.com/26287042/100246279-3b550100-2f39-11eb-93b4-653ba39b589c.JPG)

**Comment by Robertschv** [comment]
Hello @BestiaPL, it looks like the text is now being translated correctly. I saw the error before, I am happy that it is now fixed.

I haven't tried the Free download manager in a while on Windows, but have you tried it again?

**Comment by BestiaPL** [comment]
Checked on version: 6.16.2.4586 (232d605) / May, 16, 2022/:

![image](https://user-images.githubusercontent.com/26287042/171049634-f6d486d8-4304-4125-bdf5-5384d9ceda51.png)
