### ISSUE TITLE
Multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [FreeDownloadManagerTeam/FDM6-localization#213]
@FreeDownloadManagerTeam 

I checked that your exe installer is based on Inno Setup.
I opened your installer and modified it to make it multilanguage (I addeded italian).
The changes is very fast and just require very short changes only in "Languages" and "Custom messages" section of Inno Setup file.

[CustomMessages]
english.NameAndVersion=%1 version %2
english.AdditionalIcons=Additional shortcuts:
english.CreateDesktopIcon=Create a &desktop shortcut
english.CreateQuickLaunchIcon=Create a &Quick Launch shortcut
english.ProgramOnTheWeb=%1 on the Web
english.UninstallProgram=Uninstall %1
english.LaunchProgram=Launch %1
english.AssocFileExtension=&Associate %1 with the %2 file extension
english.AssocingFileExtension=Associating %1 with the %2 file extension...
english.AutoStartProgramGroupDescription=Startup:
english.AutoStartProgram=Automatically start %1
english.AddonHostProgramNotFound=%1 could not be located in the folder you selected.%n%nDo you want to continue anyway?

italian.NameAndVersion=%1 versione %2
italian.AdditionalIcons=Collegamenti aggiuntivi:
italian.CreateDesktopIcon=Crea collegamento &desktop
italian.CreateQuickLaunchIcon=Crea collegamento &Avvio rapido
italian.ProgramOnTheWeb=Sito web %1
italian.UninstallProgram=Disinstalla %1
italian.LaunchProgram=Esegui %1
italian.AssocFileExtension=&Associa '%1' con l'estensioen file '%2'
italian.AssocingFileExtension=Associazione di '%1' con i fiel cone stensione '%2'...
italian.AutoStartProgramGroupDescription=Avvio automatico:
italian.AutoStartProgram=Avvia automaticamente '%1'
italian.AddonHostProgramNotFound='%1' non trovato nella cartella selezionata.%n%nVuoi continuare comunque?

[Languages]
; These files are stubs
; To achieve better results after recompilation, use the real language files
Name: "english"; MessagesFile: "C:\Program Files (x86)\Inno Setup 6\default.isl"; 
Name: "italian"; MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Italian.isl"; 

In the same way it's easy to add other languages.

Could be an idea also to make a changes in first string as I did to add "(32bit) or "(64bit)" to qualify in the window title and program description what kind of installer is.

[Setup]
AppVerName=Free Download Manager 6.14.0.3798 (64bit)

**Comment by lychichem** [comment]
@bovirus Have you ever made the uninstaller multilingual? If a multilingual installer is distributed, users will think the uninstaller should also be multilingual.

**Comment by bovirus** [comment]
@lychichem 

I didn't undersand about it.
The installer maker use the language strings for installer and also uninstaller.

**Comment by lychichem** [comment]
> @lychichem
> 
> I didn't undersand about it.
> The installer maker use the language strings for installer and also uninstaller.

There is  a string in uninstaller says "Do you want to uninstall xxx and all its components?" However in your example I didn't see it.

**Comment by bovirus** [comment]
@lychichem

When I can see the original inno setup script I can provide you mroe details.
Most of the inno Setup common strings are already included in base Inno Setup .isl language file (ex. Italian.isl for Italian language).
My strings are an example.
I down't know which Inno Setup version is used to create the installer and what version is basic Italin language file (Italian.isl).

**Comment by lychichem** [comment]
> @lychichem
> 
> When I can see the original inno setup script I can provide you mroe details.
> Most of the inno Setup common strings are already included in base Inno Setup .isl language file (ex. Italian.isl for Italian language).
> My strings are an example.
> I down't know which Inno Setup version is used to create the installer and what version is basic Italin language file (Italian.isl).

Sorry, I mixed up Inno Setup and NSIS... Maybe you are right but we need to consider installer and uninstaller at the same time.

**Comment by BestiaPL** [comment]
InnoSetup is already translated into multiple languages.
Just look at: https://jrsoftware.org/files/istrans/
This is easy to implement into installer and it will be great for non-English language users.

**Comment by bovirus** [comment]
@BestiaPL 

Inno Setup is only the installer maker.
Then the standard Inno Setup messagers are already translated.
But the custom messages (specific for FDM) should be translated.

**Comment by bovirus** [comment]
This is the new installer 6.14.2.3973 64bit (just for test - is not officila!!!)

Add three languages (Italian, French, German)
Set some file properties missing like version (was 0.0.0.0) and copyright (was empty)

https://mega.nz/file/qNpVnQqI#pHiWbz3X4XpJZrcwuNl0a3mA4cxQyAVtmv2_qIShNE8

Is just for FDM dveloper to check that it's poossible to do it.
Of coutrse I can provdie my Inno Setup iss script with all tweaks.

**Comment by BestiaPL** [comment]
I've checked your installer. This is IS 6.2.0 - and I didn't read any non standard dialog windows (or strings).

So, maybe you can put non-standard text on repository so you could make create multilanguage installer.

**Comment by BestiaPL** [comment]
If you can - i would be nice :) Of course, i will let you know if something will be not translated into Polish.

**Comment by bovirus** [comment]
@BestiaPL 

Updated test installer wuiths everal language.

The link is mega link posted before (updated)

Note: for this exe installer I used Inno Setup 5.6.1 unicode (instread InnOS etup 6) because in IS 6 for many non standard languages the translations is not updated (instead with IS 5 are updated).

**Comment by bovirus** [comment]
@BestiaPL 

Did you test new installer with many language (Polish included)?

**Comment by BestiaPL** [comment]
I've checked installer on my PC, also on clean PC with Win10 x64. In both cases everything was ok. There was not any dialog windows not translated into Polish.
Thanks :)

**Comment by FreeDownloadManagerTeam** [comment]
Hello,
We'll think about it.

**Comment by FreeDownloadManagerTeam** [comment]
Will be added in the next update.
