### ISSUE TITLE
Translation Template

### ISSUE THREAD

**Issue by MathiasDevelopes** [FreeDownloadManagerTeam/FDM6-localization#278]
Is there a translation template for poedit? I don't have a translation template for a language I want to translate (Norwegian Bokmal)

**Comment by samiulislamsharan** [comment]
I'm also looking for a poedit template as I want to translate to Bengali (Bangladesh)

**Comment by shakib04** [comment]
> I'm also looking for a poedit template as I want to translate to Bengali (Bangladesh)

I want to involve in Bangla translation. Have you started your work?

**Comment by FreeDownloadManagerTeam** [comment]
Hello,
We can create the required templates for you. Just request it using our forum (https://www.freedownloadmanager.org/board/viewforum.php?f=2) or support form (https://www.freedownloadmanager.org/support.htm).
