### ISSUE TITLE
not able to download youtube videos from fdm anymore

### ISSUE THREAD

**Issue by abhisheks26** [FreeDownloadManagerTeam/FDM6-localization#279]
I'm facing issues while downloading youtube videos using FDM it says youtube video download not available please help me with this and solve this as soon as possible
![Uploading Screenshot 2021-11-09 191116.jpg…]()

**Comment by FreeDownloadManagerTeam** [comment]
Hello,

The problem is recurring. The Youtube download is temporarily
disabled until we resolve this issue, which will hopefully be soon.

вт, 9 нояб. 2021 г. в 16:41, abhisheks26 ***@***.***>:
