### ISSUE TITLE
Not able to download youtube

### ISSUE THREAD

**Issue by Intoy0711** [FreeDownloadManagerTeam/FDM6-localization#282]
How can I download youtube please.

**Comment by iammursalin** [comment]
> The Youtube download is temporarily disabled
By the word "temporarily" we can hope that the feature will return.

I just read in an article that you (FDM) had received a claim from Google. So you had to disable the feature.
That was an article from Oct 2021, and you posted this reply 10 days ago.
So there is hope that it'll return.

Please work on this feature.
Thanks.

**Comment by iammursalin** [comment]
> The Youtube download is temporarily disabled

By the word "temporarily" we can hope that this feature will return.

I just read in an article that you (FDM) had received a claim from Google. So you had to disable the feature.
That was an article from Oct 2021, and you posted this reply 10 days ago.
So there is hope that it'll return.

Please work on this feature.
Thanks.

**Comment by ENTPRESTIGIOUS** [comment]
A temporary workaround: https://github.com/jely2002/youtube-dl-gui
