### ISSUE TITLE
Error in the detection of the Spanish language (ARG).

### ISSUE THREAD

**Issue by ArmorKeik** [FreeDownloadManagerTeam/FDM6-localization#289]
I have Windows 10 in the Spanish language of Argentina.
Then the program will have detected it, but instead of replacing it with the Spanish of Spain the program appears in English but saying "Spanish (Argentina)".

![image](https://user-images.githubusercontent.com/87909542/153943378-5bc7fb93-100e-48b1-b0e6-c2d058a02006.png)

I report this because I found this very strange, and much more if the flag of England appears next to the "Argentine" language.

![image](https://user-images.githubusercontent.com/87909542/153943613-d7eac980-248e-4dca-83f7-d3d904cd98c0.png)

I was able to solve it by changing the language to Spanish, but it was a funny experience for me (due to the raw history between the two countries).

_I wrote all this from a translator, so there may be errors._

**Comment by FreeDownloadManagerTeam** [comment]
Thank you for the report! It will be fixed in the next version of FDM.
