### ISSUE TITLE
Translation in Bengali Language

### ISSUE THREAD

**Issue by shakib04** [FreeDownloadManagerTeam/FDM6-localization#366]
Hello FDM, 
Greetings! I am going to add Bengali translation for FDM. Already I have started my work. It will take some time. Maybe I will not full time involve in this work. Would you accept it?

**Comment by shakib04** [comment]
I need confirmation from the authority.

**Comment by FreeDownloadManagerTeam** [comment]
Just make sure if FDM was not translated to it already. If not - feel free to translate and send us a pull request.
