### ISSUE TITLE
Change the length of the browser integration button

### ISSUE THREAD

**Issue by VenusGirl** [FreeDownloadManagerTeam/FDM6-localization#420]
![FDM00](https://github.com/FreeDownloadManagerTeam/FDM6-localization/assets/53147200/bb68c3f5-74c5-4463-b822-93febe285dc2)

The browser integration button is short, so I think we need to increase the length so that the phenomenon of two lines appears to be one line.

**Comment by FreeDownloadManagerTeam** [comment]
Hello,
Will be fixed in the next update of FDM.
