### ISSUE TITLE
From browser integration.....

### ISSUE THREAD

**Issue by VenusGirl** [FreeDownloadManagerTeam/FDM6-localization#438]
When translating, only Google Chrome will be in two lines.
It doesn't look good, so please increase the length to make it look like a single line.

![이미지 001](https://github.com/FreeDownloadManagerTeam/FDM6-localization/assets/53147200/d6c61ba3-4eab-442b-98b9-cde40acf6945)

**Comment by FreeDownloadManagerTeam** [comment]
https://github.com/FreeDownloadManagerTeam/FDM6-localization/issues/420

?
