### ISSUE TITLE
Inno installation script with Korean

### ISSUE THREAD

**Issue by VenusGirl** [FreeDownloadManagerTeam/FDM6-localization#460]
I request you to add Korean to the installation screen.

Attached is the Inno installation script with Korean.

[Korean_script.iss.zip](https://github.com/FreeDownloadManagerTeam/FDM6-localization/files/13714883/Korean_script.iss.zip)

![Korean_script](https://github.com/FreeDownloadManagerTeam/FDM6-localization/assets/53147200/e27eaac5-a3a1-4d09-aaab-426ec94a69f4)

**Comment by FreeDownloadManagerTeam** [comment]
Hello,
Thank you for your work. 
Will be added in the next update of FDM.
