### ISSUE TITLE
Option to maintain main window minimized

### ISSUE THREAD

**Issue by bovirus** [FreeDownloadManagerTeam/FDM6-localization#507]
@FreeDownloadManagerTeam 

Is there an option to maintain always minimized main/download list window?

If is not there could be add it in next release?

I started with FDM minimzed in system tray bar.

Whrn I click on  a download link appear the downlaod list window and window with info about downlaod folder and file name.

When I conferm click on 'DOWNLOAD' button the small window (folder/file name to download) disappear but remain opened the main /download list window.

My scope i to have always main/downlaod list window minimzed and have visible only the window where set download folder/file name to download.

Thanks.

![image](https://github.com/FreeDownloadManagerTeam/FDM6-localization/assets/1262554/b960114f-cd1f-400c-8a40-d9871a4af099)
Click on download link open Download list window and Save file dialog

![image](https://github.com/FreeDownloadManagerTeam/FDM6-localization/assets/1262554/a18dbac0-5fe1-49ba-8714-83b3e1c9eadd)
When confirm remain open Download list window

**Comment by FreeDownloadManagerTeam** [comment]
You can use FDM forum to ask such questions. 
https://www.freedownloadmanager.org/board/viewforum.php?f=1
I think you need to enable standalone create new downloads windows option. It's located in Preferences | Advanced section.
