### ISSUE TITLE
Islamic-App

### ISSUE THREAD

**Issue by mouradkoudid** [FreeDownloadManagerTeam/FDM6-localization#543]
``<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تطبيق إسلامي</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>تطبيق إسلامي</h1>
    </header>
    <section id="prayer-times">
        <h2>أوقات الصلاة</h2>
        <ul>
            <li id="fajr">الفجر: </li>
            <li id="dhuhr">الظهر: </li>
            <li id="asr">العصر: </li>
            <li id="maghrib">المغرب: </li>
            <li id="isha">العشاء: </li>
        </ul>
    </section>
    <section id="daily-adhkar">
        <h2>أذكار الصباح والمساء</h2>
        <div>
            <h3>أذكار الصباح</h3>
            <p>اللّهـمَّ أَنْتَ رَبِّـي، لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك...</p>
        </div>
        <div>
            <h3>أذكار المساء</h3>
            <p>اللّهـمَّ أَنْتَ رَبِّـي، لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك...</p>
        </div>
    </section>
    <section id="quran-duas">
        <h2>القرآن والأدعية</h2>
        <ul>
            <li><a href="https://quran.com" target="_blank">قراءة القرآن الكريم</a></li>
            <li><a href="https://www.duas.org" target="_blank">مجموعة من الأدعية</a></li>
            <li><a href="https://sunnah.com" target="_blank">الأحاديث النبوية</a></li>
        </ul>
    </section>
    <footer>
        <p>&copy; 2024 تطبيق إسلامي</p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/praytimes/2.4.0/PrayTimes.min.js"></script>
    <script src="script.js"></script>
</body>
</html>
body {
    font-family: Arial, sans-serif;
    direction: rtl;
    text-align: center;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding-top: 60px; /* Space for fixed header */
}

header {
    background-color: #4caf50;
    color: white;
    padding: 1em 0;
    position: fixed;
    width: 100%;
    top: 0;
    left: 0;
    z-index: 1000;
}

section {
    margin: 2em 0;
    padding: 0 1em;
}

h1, h2, h3 {
    margin: 0.5em 0;
}

ul {
    list-style: none;
    padding: 0;
}

li {
    background-color: white;
    margin: 0.5em 0;
    padding: 0.5em;
    border-radius: 5px;
    box-shadow: 0 0 5px rgba(0,0,0,0.1);
    transition: background-color 0.3s;
}

li:hover {
    background-color: #e0f7fa;
}

li a {
    text-decoration: none;
    color: #333;
}

footer {
    background-color: #333;
    color: white;
    padding: 1em 0;
    position: fixed;
    width: 100%;
    bottom: 0;
}
document.addEventListener('DOMContentLoaded', function() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPrayerTimes, showError);
    } else {
        alert('تحديد الموقع الجغرافي غير مدعوم في هذا المتصفح.');
    }
});

function showPrayerTimes(position) {
    const latitude = position.coords.latitude;
    const longitude = position.coords.longitude;
    
    const prayTimes = new PrayTimes('Makkah');
    const times = prayTimes.getTimes(new Date(), [latitude, longitude], +3);

    document.getElementById('fajr').textContent += times.fajr;
    document.getElementById('dhuhr').textContent += times.dhuhr;
    document.getElementById('asr').textContent += times.asr;
    document.getElementById('maghrib').textContent += times.maghrib;
    document.getElementById('isha').textContent += times.isha;
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            alert('تم رفض طلب تحديد الموقع الجغرافي.');
            break;
        case error.POSITION_UNAVAILABLE:
            alert('معلومات الموقع غير متوفرة.');
            break;
        case error.TIMEOUT:
            alert('انتهت مهلة تحديد الموقع.');
            break;
        case error.UNKNOWN_ERROR:
            alert('حدث خطأ غير معروف.');
            break;
    }
}

**Comment by FreeDownloadManagerTeam** [comment]
What is this?

**Comment by FreeDownloadManagerTeam** [comment]
...
