### ISSUE TITLE
Add unlisted language

### ISSUE THREAD

**Issue by Kamilake** [FreeDownloadManagerTeam/FDM6-localization#71]
I apologize if this is stupid question.

I want to translate FDM into Korean but it was not on the list.
Can I create a new language that doesn't exist in the list?
![image](https://user-images.githubusercontent.com/15166740/85917135-9dc6aa00-b892-11ea-9a7b-c5444520df72.png)

If possible, can I just create a new file and work on it?
Thanks for your help.(I'm new to GitHub, I apologize for this)

Regards.

**Comment by FreeDownloadManagerTeam** [comment]
Hello!

We have added the Korean translation files to our repository.
You can create your fork, commit changes, then request a pull.
Here is the documentation https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks

Thank you for your cooperation!

**Comment by Kamilake** [comment]
Thank you. I'll try that!
